# Generated by Django 3.0.7 on 2020-06-16 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200616_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
