# Generated by Django 3.0.7 on 2020-06-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200614_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Replies'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
