# Generated by Django 3.0.7 on 2020-06-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
